#!/usr/bin/env node

import { Command } from 'commander';
import chalk from 'chalk';
import * as fs from 'fs';
import * as readline from 'readline';
import { ReActAgent, calculatorTool, currentTimeTool } from './index';

const program = new Command();

program
  .name('ai-agent')
  .description('AI agent framework scaffolding. ReAct, tool-use, planning agents.')
  .version('1.0.0');

// Demo command
program
  .command('demo')
  .description('Run demo agent with built-in tools')
  .argument('[task]', 'Task for the agent')
  .option('-v, --verbose', 'Show agent steps')
  .action(async (task, options) => {
    const agent = new ReActAgent({
      name: 'DemoAgent',
      tools: [calculatorTool, currentTimeTool],
      verbose: options.verbose,
    });

    if (task) {
      try {
        console.log(chalk.cyan('\n🤖 Running agent...\n'));
        const result = await agent.run(task);
        console.log(chalk.green('\nAnswer:'), result.answer);
        console.log(chalk.gray(`\nIterations: ${result.iterations}`));
      } catch (error) {
        console.error(chalk.red('Error:'), error instanceof Error ? error.message : error);
      }
    } else {
      // Interactive mode
      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
      });

      console.log(chalk.cyan('\n🤖 Interactive Agent Demo'));
      console.log(chalk.gray('Tools: calculator, get_time'));
      console.log(chalk.gray('Type "exit" to quit\n'));

      const ask = () => {
        rl.question(chalk.green('You: '), async (input) => {
          if (input.toLowerCase() === 'exit') {
            rl.close();
            return;
          }

          try {
            const result = await agent.run(input);
            console.log(chalk.cyan('Agent:'), result.answer, '\n');
          } catch (error) {
            console.error(chalk.red('Error:'), error instanceof Error ? error.message : error);
          }

          ask();
        });
      };

      ask();
    }
  });

// Init command
program
  .command('init')
  .description('Generate agent scaffolding for your project')
  .option('-d, --dir <path>', 'Output directory', './lib/agent')
  .option('-t, --type <type>', 'Agent type (react|simple|planning)', 'react')
  .option('--js', 'Generate JavaScript')
  .action((options) => {
    const ext = options.js ? 'js' : 'ts';
    const dir = options.dir;

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const code = `// AI Agent
// Generated by ai-agent

import OpenAI from 'openai';
import { z } from 'zod';

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

${options.js ? '' : `export interface Tool {
  name: string;
  description: string;
  parameters: z.ZodType<any>;
  execute: (params: any) => Promise<string>;
}

`}export function defineTool${options.js ? '' : '<T extends z.ZodType<any>>'}(
  name${options.js ? '' : ': string'},
  description${options.js ? '' : ': string'},
  parameters${options.js ? '' : ': T'},
  execute${options.js ? '' : ': (params: z.infer<T>) => Promise<string>'}
)${options.js ? '' : ': Tool'} {
  return { name, description, parameters, execute };
}

export class Agent {
  private tools${options.js ? '' : ': Map<string, Tool>'} = new Map();
  private model${options.js ? '' : ': string'};
  private systemPrompt${options.js ? '' : ': string'};

  constructor(config${options.js ? ' = {}' : '?: { model?: string; systemPrompt?: string }'}) {
    this.model = config?.model || 'gpt-4-turbo';
    this.systemPrompt = config?.systemPrompt || 'You are a helpful AI assistant.';
  }

  addTool(tool${options.js ? '' : ': Tool'}) {
    this.tools.set(tool.name, tool);
  }

  async run(input${options.js ? '' : ': string'})${options.js ? '' : ': Promise<string>'} {
    const messages${options.js ? '' : ': OpenAI.ChatCompletionMessageParam[]'} = [
      { role: 'system', content: this.systemPrompt },
      { role: 'user', content: input },
    ];

    const tools = Array.from(this.tools.values()).map(t => ({
      type: 'function' as const,
      function: {
        name: t.name,
        description: t.description,
        parameters: { type: 'object', properties: {} }, // Simplified
      },
    }));

    for (let i = 0; i < 10; i++) {
      const response = await openai.chat.completions.create({
        model: this.model,
        messages,
        tools: tools.length > 0 ? tools : undefined,
      });

      const message = response.choices[0].message;

      if (message.tool_calls?.length) {
        messages.push(message);

        for (const call of message.tool_calls) {
          const tool = this.tools.get(call.function.name);
          if (tool) {
            const args = JSON.parse(call.function.arguments);
            const result = await tool.execute(args);
            messages.push({
              role: 'tool',
              tool_call_id: call.id,
              content: result,
            });
          }
        }
      } else {
        return message.content || '';
      }
    }

    throw new Error('Max iterations');
  }
}
`;

    fs.writeFileSync(`${dir}/agent.${ext}`, code);
    console.log(chalk.green(`✓ Created ${dir}/agent.${ext}`));

    // Tools file
    const toolsCode = `// Agent Tools
// Generated by ai-agent

import { z } from 'zod';
import { defineTool } from './agent';

export const calculatorTool = defineTool(
  'calculator',
  'Evaluate math expressions',
  z.object({ expression: z.string() }),
  async ({ expression }) => {
    try {
      return String(new Function(\`return \${expression}\`)());
    } catch {
      return 'Error: Invalid expression';
    }
  }
);

export const timeTool = defineTool(
  'get_time',
  'Get current date/time',
  z.object({}),
  async () => new Date().toISOString()
);
`;

    fs.writeFileSync(`${dir}/tools.${ext}`, toolsCode);
    console.log(chalk.green(`✓ Created ${dir}/tools.${ext}`));

    console.log(chalk.cyan('\n✅ Agent scaffolding generated!\n'));
    console.log(chalk.gray(`  import { Agent } from '${dir}/agent';`));
    console.log(chalk.gray(`  import { calculatorTool } from '${dir}/tools';`));
    console.log(chalk.gray(`  const agent = new Agent();`));
    console.log(chalk.gray(`  agent.addTool(calculatorTool);`));
    console.log(chalk.gray(`  await agent.run('Calculate 2+2');`));
  });

// Info command
program
  .command('info')
  .description('Show agent info')
  .action(() => {
    console.log(chalk.cyan('\n🤖 AI Agents\n'));

    console.log(chalk.bold('Agent Types:'));
    console.log('  • ReAct - Reason + Act loop with tools');
    console.log('  • Simple - Single LLM call');
    console.log('  • Planning - Plan then execute\n');

    console.log(chalk.bold('Quick Start:'));
    console.log(chalk.gray('  npx ai-agent demo "What is 25 * 4?"'));
    console.log(chalk.gray('  npx ai-agent init'));
  });

program.parse();
